package com.wastemanagement.wastesystem.model;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Represents an individual, per-user alert — typically system-generated
 * as a side effect of some other action in the app (e.g. "Your complaint
 * has been resolved", "You earned 10 reward points", "A penalty has been
 * issued to your account").
 *
 * Distinct from Announcement.java, which is admin-authored broadcast
 * content visible to many users at once. A Notification always targets
 * exactly one recipient (userId) and is generated by the relevant service
 * (ComplaintService, RewardService, PenaltyService, etc.) at the moment
 * the triggering event occurs, rather than authored directly by an admin.
 *
 * Read/unread state is tracked per-notification (read flag) so the
 * frontend can show an unread-count badge and mark-as-read behavior,
 * consistent with a standard in-app notification center UX.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "notifications")
public class Notification {

    @Id
    private String id;

    /**
     * References User.id of the recipient — kept as userId (the common
     * identity root) so a single Notification type can target any of the
     * three roles (a citizen's reward alert, a worker's route-assignment
     * alert, an admin's system alert) without needing separate
     * per-role notification collections.
     */
    @NotBlank(message = "Recipient is required")
    @Indexed
    private String userId;

    @NotBlank(message = "Title is required")
    private String title;

    @NotBlank(message = "Message is required")
    private String message;

    /**
     * Free-text category (e.g. "COMPLAINT_UPDATE", "REWARD_CREDITED",
     * "PENALTY_ISSUED", "SCHEDULE_CHANGE", "ANNOUNCEMENT"). Kept as a plain
     * string, mirroring AuditLog.action, since new notification-triggering
     * events will be added across services over time without needing to
     * modify this core model each time (Rule 18).
     */
    private String type;

    /**
     * References the id of the entity this notification relates to (e.g.
     * a Complaint.id, Reward.id, Penalty.id) so tapping the notification
     * on the frontend can deep-link to the relevant detail screen.
     * Nullable — some notifications (e.g. a general system message) don't
     * reference a specific entity.
     */
    private String relatedEntityId;

    /**
     * Whether the recipient has read this notification yet — drives the
     * unread-count badge and lets the frontend mark it as read once
     * opened.
     */
    @Builder.Default
    private boolean read = false;

    @CreatedDate
    @Indexed
    private LocalDateTime createdAt;
}