package com.wastemanagement.wastesystem.model;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Represents a single reward-points transaction credited to a citizen.
 *
 * Rather than only storing a running total on Citizen.rewardPoints (which
 * already exists as a denormalized counter for quick display), each award
 * is also logged here as an individual ledger entry. This gives:
 * - An auditable history ("why does this citizen have 340 points?")
 * - The ability to reverse/adjust a specific award if a worker's
 *   segregation-compliance assessment is later disputed or corrected
 * - Data for a "Rewards" screen showing a citizen their earning history,
 *   not just a single number
 *
 * A Reward is typically created automatically by RewardService (upcoming)
 * when a CollectionRecord is logged with segregationCompliant = true, but
 * the model also supports a manual award by the Super Admin (e.g. a
 * one-off community recognition bonus) via the createdBy field.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "rewards")
public class Reward {

    @Id
    private String id;

    /**
     * References Citizen.id — the citizen credited with these points.
     * Required: every reward must be attributable to a citizen.
     */
    @NotBlank(message = "Citizen is required")
    @Indexed
    private String citizenId;

    /**
     * References CollectionRecord.id, if this reward was auto-generated
     * from a compliant collection. Nullable — a manually awarded bonus
     * (e.g. community recognition) has no underlying collection record.
     */
    private String collectionRecordId;

    @NotNull(message = "Points is required")
    private Integer points;

    /**
     * Free-text reason (e.g. "Proper waste segregation", "Community
     * Cleanliness Drive Bonus"). Kept as a plain string rather than an enum
     * since award reasons are open-ended and admin-authored bonuses need
     * a custom description (Rule 18).
     */
    @NotBlank(message = "Reason is required")
    private String reason;

    /**
     * References User.id of the Super Admin who manually issued this
     * reward. Null when the reward was auto-generated by the system from
     * a compliant CollectionRecord rather than manually awarded.
     */
    private String createdBy;

    @CreatedDate
    private LocalDateTime createdAt;
}